### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by gdalle** [mitmath/JuliaComputation#1]
The link to the installation instructions in Homework 0 is broken. Perhaps it would be nice to have a local page for this class regarding setup, instead of redirecting to the old "Computational thinking"

**Comment by alanedelman** [comment]
which link is broken?  we don;t think of the old "computational thinking" as old...
we'd like to make it timeless

**Comment by alanedelman** [comment]
yehh that should be futureproofed to be the latest stable julia

**Comment by fonsp** [comment]
Added a link to our automatically future-proofed install instructions on computationalthinking.mit.edu 

in https://github.com/mitmath/JuliaComputation/commit/62510e8dd05742703a92fd49de30244f27c5656d
